### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by cm-mojo** [malcolmrigg/WizardClock#17]
Hi, can you explain how to format using the font store in the www/custom-lovelace folder? i have downloaded BITCBLKAD.ttf but can't get it used in the dashboard

**Comment by malcolmrigg** [comment]
Hi - the example in the readme shows you how to configure it, basically copy the font into your www/custom-lovelace folder then put something like this in the config for the card:

fontname: itcblkad_font
fontface: >-
  font-family: itcblkad_font;    src: local(itcblkad_font),
  url('/local/custom-lovelace/ITCBLKAD.TTF') format('opentype');

("ITCBLKAD.TTF" is the font file I used - you may need to change the above config to match your "BITCBLKAD.ttf" file, and perhaps the name of the font in the font-family/fontname bits too).

Note that the "www" folder in your config folder maps to the URL "/local/" which is why the URL doesn't have the "www" in it.

**Comment by cm-mojo** [comment]
this is the folder the ttf is in:

![image](https://github.com/user-attachments/assets/572d7f64-6c97-4845-8ed3-4a589648f571)

and this is the config:

fontname: bitcblkad_font
fontface: >-
  font-family: bitcblkad_font; src: local(bitcblkad_font),
  url('/local/custom-lovelace/BITCBLKAD.ttf') format('opentype');
width: 500

Still doesn't work....not sure what I'm doing wrong

**Comment by malcolmrigg** [comment]
Sorry, I'm really not an expert on web fonts, I figured it out by experimenting and looking at how other people did it. Maybe try experimenting with the format option - although opentype worked for me your particular version of the font looks like it could be truetype? 

Also, maybe try incrementing the version number in the resources (as if you were updating to a new version of the code). You could also try adding the font file itself to the resources as a stylesheet. Not sure what else to suggest, maybe there's a webfont guru out there that'll be able to help...

**Comment by cm-mojo** [comment]
no worries, thanks - just wanted to make sure I wasn't missing something obvious

**Comment by cm-mojo** [comment]
can you upload the font you have used to see if I can mimic the behaviour?

**Comment by jteijema** [comment]
I have the same issues with the font. You might adding the font to the resources too via the settings.

In the end I just edited the JS. 

Replace this block:
```javascript
var fontstyle = document.createElement('style');
if (this.config.fontface) {
    console.log("Applying custom font-face:", this.config.fontface);
    fontstyle.innerText = "@font-face { " + this.config.fontface + " }  ";
} else {
    console.log("Applying default font-face.");
    fontstyle.innerText = "@font-face { font-family: itcblkad_font; src: local(itcblkad_font), url('/local/ITCBLKAD.TTF') format('opentype'); }  ";
}
```
With this updated code:
```javascript
var fontstyle = document.createElement('style');

// Define the font-face rule dynamically
this.selectedFont = this.config.fontName ? this.config.fontName : "Poppins"; // Use Poppins as default

// Use Base64 if applicable or reference local file
const fontFaceCSS = `
    @font-face {
        font-family: "${this.selectedFont}";
        src: url('data:font/woff2;base64,d09GMgABAAAAAB7MAAwAAAAAP6AAAB54AAE...') format('woff2'); /* Base64 font */
        font-weight: normal;
        font-style: normal;
    }
`;
console.log("Applying font-face:", fontFaceCSS);
fontstyle.innerText = fontFaceCSS;
document.head.appendChild(fontstyle);
```

oh yeah you'll need to change your font file to b64. Lots of converters online. Note that I am running on PR #28

**Comment by pcondon10** [comment]
I'm continuing to struggle with fonts for this (awesome) widget.  I have a font installed and can use it in other cards but if I reference it here it just doesn't work.  I'm attaching a couple screenshots and the YAML for those cards here.  You can see the font working in the one card "Hello Pete!" yet in this one it doesn't work when referenced as a font face... I've tried placing it in the local folder, encoding it as WOFF2 and even BASE64 encoding it.  Nothing seems to have worked.  Wondering if anyone can help.

![Image](https://github.com/user-attachments/assets/ea252822-3f51-4db8-b545-08d44c788775)

Title Card YAML looks like this:
```
type: custom:mushroom-title-card
title: Hello, {{ user }} !
card_mod:
  style: |
    ha-card {
      font-family: "henny penny";
    }
```

Wizard Card YAML looks like this:
```
type: custom:wizard-clock-card
locations: null
min_location_slots: 0
wizards:
  - entity: person.pete
    name: Pete
    colour: Black
    textcolour: White
  - entity: person.kristen
    name: Kristen
    colour: Black
    textcolour: White
  - entity: person.norah
    name: Norah
    colour: Black
    textcolour: White
  - entity: person.cate
    name: Cate
    colour: Black
    textcolour: White
  - entity: person.mere
    name: Mere
    colour: Black
    textcolour: White
fontname: HennyPenny
fontface: >-
  font-family: HennyPenny; src: local(HennyPenny), url('/local/hennypenny.woff')
  format('woff2');
width: 350
travelling: Somewhere
```

Keep in mind, this is about the 10th iteration of YAML.  I've tried using the format like the following (with the local location pointing to the actual HennyPenny font I placed locally):
```
fontface: >-
  font-family: itcblkad_font;    src: local(itcblkad_font),
  url('/local/custom-lovelace/ITCBLKAD.TTF') format('opentype');

```

Any help is greatly appreciated!
