### ISSUE TITLE
Internationalization Issue? "Zuhause" is not "Home"

### ISSUE THREAD

**Issue by Rene-Welbers** [malcolmrigg/WizardClock#27]
Hey,

i just configured the wizard clock, my wife will love it :)

But unfortunately it seems, that locations in an other language will not get mapped? 

For e.g. i'm in germany, therefore my "Home" is named "Zuhause". 

Our location tracker used in the clock will report that, too:

![Image](https://github.com/user-attachments/assets/5346d496-1b34-4fed-9138-8824ffce11d7)

But the clock will stick the hands to the top, doesn't matter if i add manual locations (Then the first is always on top) or not

My config:
```yaml
type: custom:wizard-clock-card
width: 300
wizards:
  - entity: device_tracker.rene_handy
    name: René
    colour: "#025ab8"
  - entity: device_tracker.lydia_handy_2
    name: Lydia
    colour: "#116900"
lost: Lost
travelling: Hier und da
fontname: itcblkad_font
fontface: >-
  font-family: itcblkad_font;    src: local(itcblkad_font),
  url('/local/custom-lovelace/ITCBLKAD.TTF') format('opentype');
```

Result:

![Image](https://github.com/user-attachments/assets/cb3fb802-f6b2-4e56-b839-7fa68961b8c8)
