### ISSUE TITLE
[Feature Request] Custom Location Names & Merged Locations

### ISSUE THREAD

**Issue by josh-justjosh** [malcolmrigg/WizardClock#31]
Would it be possible to customise the location names displayed on the card? Further then to that: if one were to set the same custom location name for multiple locations as they are defined in home assistant, can these be shown as one merged location (obviously with the same name) in the card?

Use case: I have my family members' locations in home assistant using the google maps api and they're widely spread over the country, so I have a few zones in various places that ideally I'd merge together on this card.

Possible config suggestion:

```
locations:
  # 'classic' simple location
  - Home
 
  # renaming a location
  - name: 'Short Place'
    zone: zone.place_with_long_name_in_HA

  # merged place
  - name: 'Uni'
    zones:
    - zone.uni_site1
    - zone.uni_site2
```

Thanks for this great card!
